app1/urls.py
from app1.views import *
from django.urls import path

app_name='anything'

urlpatterns=[
    path('chamu/',chamu,name='chamu')
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'

urlpatterns=[
    path('response/',response,name='response')
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include

import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def chamu(request):
    return render(request,'chamu.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def response(request):
    return render(request,'response.html')

templates/chamu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>heyy hiii.......chamu</h1>
        <h1> wt doing</h1>
        <a href="{% url 'nothing:response' %}"><h1> response</h1></a>
    </center>
</body>
</html>

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> heyyy hiii...</h1>
        <h1>nothing.....</h1>
        <a href="{% url 'anything:chamu' %}"><h1>response to  chamu</h1></a>
    </center>
</body>
</html>